### ISSUE TITLE
Achievements not unlocking?

### ISSUE THREAD

**Issue by ryuugaplays** [Eveldee/NobetaTrainer#2]
Hello, I have downloaded your trainer in hopes of speedrunning the last few achievements I missed. But it would seem that the achievements does not unlock when playing with the trainer? 
Is there something I'm missing?

**Comment by Eveldee** [comment]
Hello,

Yes this is happening because the loading from Steam is disabled by default for multiple reasons. If you want to reenable it, follow those instructions:
- Go the game installation with the trainer installed
- Open the directory `LittleWitchNobeta_Data\Plugins\x86_64`
- Delete `steam_appid.txt` and replace `steam_api64.dll` with the one from your original game installation
- Add the game to Steam manually and start it from Steam

If you cannot find the original files, do a game repair in Steam
